title: Import Google fonts
hero_image: images/banner.png
description: How to import Google fonts
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: How to import Google fonts
